blank_issues_enabled: true
contact_links:
  - name: Sonic Pi In-thread Forum
    url: https://in-thread.sonic-pi.net
    about: You can ask and answer any questions, share your work, and chat with other people in the community here. :)
