install(DIRECTORY buffers/ DESTINATION ${ETC_INSTALL_DIR}/buffers USE_SOURCE_PERMISSIONS)
install(DIRECTORY doc/ DESTINATION ${ETC_INSTALL_DIR}/doc USE_SOURCE_PERMISSIONS)
install(DIRECTORY examples/ DESTINATION ${ETC_INSTALL_DIR}/examples USE_SOURCE_PERMISSIONS)
install(DIRECTORY samples/ DESTINATION ${ETC_INSTALL_DIR}/samples USE_SOURCE_PERMISSIONS)
install(DIRECTORY snippets/ DESTINATION ${ETC_INSTALL_DIR}/snippets USE_SOURCE_PERMISSIONS)
install(DIRECTORY synthdefs/ DESTINATION ${ETC_INSTALL_DIR}/synthdefs USE_SOURCE_PERMISSIONS)
install(DIRECTORY wavetables/ DESTINATION ${ETC_INSTALL_DIR}/wavetables USE_SOURCE_PERMISSIONS)